### ISSUE TITLE
Followup adjustments to moving to the new IT Infrastructure

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/roadmap-deprecated-2025#36]

**Comment by 0xGoerliMainnet** [comment]
block 495866

**Comment by rahmanroman1** [comment]
https://github.com/orgs/ietf-tools/projects/9/views/1?pane=issue&itemId=32888715

**Comment by MAYCHUI** [comment]
LICENSE.md

**Comment by rjsparks** [comment]
The move of everything except email systems is complete. The email migration will begin being tracked separately.

**Comment by rjsparks** [comment]
All other systems will now continue to evolve through normal processes in the new infrastructure.
